### ISSUE TITLE
Based on bug

### ISSUE THREAD

**Issue by joveice** [mashlol/StockMarket#16]
I belive the plugin works on a old vault bug where /pay -1 would take 1 from the player
since StockMarket.economy.depositPlayer(this.player.getName(), -1 * amount * stock.getPrice());
won't work. it needs to be
StockMarket.economy.withdrawPlayer(this.player.getName(), amount * stock.getPrice());
making it free to buy shares in all versions where pay -1 is patched. etc 1.8.8, other than that it works with 1.8.8 just a big flaw with that line
Old: StockMarket.economy.depositPlayer(this.player.getName(), -1 * amount * stock.getPrice());
change to : StockMarket.economy.withdrawPlayer(this.player.getName(), amount * stock.getPrice());
Please :)

**Comment by joveice** [comment]
Never used Github so im not sure where to do this "issue"

**Comment by mashlol** [comment]
On GitHub you can just propose the change to the repo, look into forking & submitting a pull request.  If you do that I'll take a look and accept your fix.

**Comment by joveice** [comment]
Sorry, i have no idea how github works or how to use pull requests

**Comment by mashlol** [comment]
Fixed in #18
