### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by Taboshkas** [mashlol/StockMarket#19]
Please update this to 1.8 as i would like to use it on my server. If you dont want to would you mind if i updated it to 1.8 and used it myself?

**Comment by mashlol** [comment]
Please feel free to update it yourself.  If you do, you should submit a pull request, it would be much appreciated!

**Comment by mashlol** [comment]
@DraksterAU it's working with 1.8 now, right?

**Comment by StargateMC** [comment]
@mashlol Yes it is, but at present only Java 8 compatible on bukkit.org as I compiled using that. Will reupload jars compiled with JDK7 shortly.

**Comment by mashlol** [comment]
Ok, let's close this then in that case.
